### ISSUE TITLE
Баг с заходом

### ISSUE THREAD

**Issue by Fersidal** [Gaprix/InSky#3]
**Описание бага**
Заходя на сервер ГО(У меня есть доступ), моментально вылетает из игры с ошибкой "Internal Server Error"

**Сервер**
СССР ГО

**Шаги воспроизведения**
Шаги для того, чтобы повторить баг
1. Заходим на сервер и ждем загрузки
2. Вылет с сервера

**Что происходит**
Вылезает окно с ошибкой "Internal Server Error"

**Демонстрация**
Скриншот/видео
(Слегка замазал скрин ошибки, т.к. высвечивается айпи)
![Без названия38_20200911070406](https://user-images.githubusercontent.com/71101440/92814380-fe7b7280-f3fd-11ea-8c15-ec6b37774550.png)
![Screenshot_20200911-055711_Minecraft](https://user-images.githubusercontent.com/71101440/92814410-0509ea00-f3fe-11ea-9d02-7dc4a8d226cc.jpg)

**Comment by Gaprix** [comment]
Устаревшая версия плагина. Перепроверьте

**Comment by Fersidal** [comment]
К сожалению ничего не сработало, так же вылетает с ошибкой "Internal server error"

**Comment by Gaprix** [comment]
Исправлено
